#postgres
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://postgres:5432/challenge
    username: username
    password: password


  #redis
  cache:
    type: redis
  data:
    redis:
      host: redis
      port: 6379

cache:
  config:
    entryTtl: 60
    post:
      entryTtl: 30